name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Cache turbo build setup
        uses: actions/cache@v3
        with:
          path: node_modules/.cache/turbo
          key: turbo-${{ github.sha }}
          restore-keys: |
            turbo-

      - name: Build all packages
        run: pnpm build

      - name: Lint
        # Will run the step even if build step failed
        if: success() || failure()
        run: pnpm lint

      - name: Test all packages
        # Will run the step even if lint step failed
        if: success() || failure()
        run: pnpm test
